worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    server {
        listen 80;
        
        # Transparent TCP proxy. We blindly forward all raw bytes to Varnish.
        # This prevents Nginx from stripping our GET request body or 
        # dropping the 'Transfer_Encoding' header.
        proxy_pass cache-layer:6081;
    }
}
